config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # get 'bookings/new'
  root to: 'pages#home'
  get 'profiles/:id/artworks', to: 'profiles#artworks', as: :profile_artworks
  get 'profiles/:id/requests', to: 'profiles#requests', as: :profile_requests
  get 'profiles/:id/bookings', to: 'profiles#bookings', as: :profile_bookings

  post 'bookings/:id/confirm', to: 'bookings#confirm', as: :bookings_confirm
  post 'bookings/:id/reject', to: 'bookings#reject', as: :bookings_reject


  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :artworks do
    resources :bookings, only: [:new, :create, :index]
  end
  resources :bookings, only: [:destroy]

  resources :profiles, except: [:index]

end

app/models/profile.rb
class Profile < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user

  mount_uploader :avatar, PhotoUploader

  validates :first_name, presence: true, allow_nil: true
  validates :last_name, presence: true, allow_nil: true
  validates :address, presence: true, allow_nil: true

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = current_user.profile
    authorize @profile
  end

  def new
  end

  def create
  end

  def edit
    @profile = current_user.profile
    session[:return_to] ||= request.referer
    authorize @profile
  end

  def update
    @profile = current_user.profile
    authorize @profile
    if @profile.update(profile_params)
      if (session[:return_to] == "http://localhost:3000/") || (session[:return_to] == "https://mona-leasing.herokuapp.com")
        redirect_to new_artwork_path
      else
        redirect_to session.delete(:return_to)
      end
    else
      render :edit
    end
  end

  def destroy
  end

  def artworks
    @profile = current_user.profile
    @artworks = policy_scope(Artwork.all) #policy_scope(current_user.artworks)
    authorize @profile
  end

  def requests
    @profile = current_user.profile
    @artworks = policy_scope(Artwork.all) #policy_scope(current_user.artworks)
    authorize @profile
  end

  def bookings
    @profile = current_user.profile
    @artworks = policy_scope(Artwork.all) #policy_scope(current_user.artworks)
    authorize @profile
  end

  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :address, :description, :avatar)
  end

end

app/views/profiles/artworks.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 col-lg-2">

      <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to "My Profile", profile_path(@profile), class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "My Artwork", profile_artworks_path(@profile), class: "active-tab nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Bookings", profile_bookings_path(@profile), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Requests", profile_requests_path(@profile), class: "nav-link"  %>
        </li>
      </ul>



    </div>
    <div class="col-12 col-lg-10">
      <h1 style="font-size: 32px; padding-bottom: 16px">My artwork</h1>
      <div class="cards pb-5">
        <% current_user.artworks.each do |artwork| %>
          <%= link_to artwork, class: "card-artwork" do %>
            <div class="card-trip">
              <img src='<%= artwork.image %>'>
                <div class="card-trip-infos">
                  <div>
                    <h2><%= artwork.title %></h2>
                    <p><%= artwork.tagline %></p>
                  </div>
                  <h2 class="card-trip-pricing" style="font-weight: 500">€<%= artwork.price %></h2>
                </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/bookings.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 col-lg-2">

      <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to "My Profile", profile_path(@profile), class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "My Artwork", profile_artworks_path(@profile), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Bookings", profile_bookings_path(@profile), class: "active-tab nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Requests", profile_requests_path(@profile), class: "nav-link"  %>
        </li>
      </ul>


    </div>
    <div class="col-12 col-lg-10">
      <h1 style="font-size: 32px; padding-bottom: 16px">My bookings</h1>
      <div class="pb-5">
        <div>
        <% current_user.bookings.each do |booking| %>
          <div style="display: flex; margin: 30px 0px">
            <div class="image-status">
              <%= link_to booking.artwork do %>
                 <img src='<%= booking.artwork.image %>' style="height: 220px; width: 300px; object-fit: cover;border-radius: 4px">
              <% end %>

              <p class="top-left" style="">Status: <%=  booking.status %> </p>
            </div>
            <div class="profile-description" style="padding: 8px 0px 8px 24px">
              <h3 style="font-weight: 700">Title: <%=  booking.artwork.title %> </h3>
              <p style="margin: 8px 0px">Price: <%=  booking.artwork.price %> </p>
              <p style="margin-top: 16px; margin-bottom: 0px">from <%= booking.start_date %></p>
                <p style="margin: 8px 0px">until <%= booking.end_date %></p>

              <%= link_to "Cancel booking", booking_path(booking), method: :delete, #data: { confirm: "Are you sure?" },
                  class: "pl-0 btn bg-transparent text-secondary mr-3",
                  style: "margin-top: 24px"  %>
              </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="pt-5 container">

  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
    <h2>Hello <%= @profile.first_name %></h2>
      <div class="mt-4 form-inputs">

        <%= simple_form_for(@profile) do |f| %>
            <%= f.input :first_name %>
            <%= f.input :last_name %>
            <div style="padding-bottom: 8px"><%= "Email" %></div>
            <div style="background-color: white; color: #495057; border-radius: 2px; padding: 6px 12px; margin-bottom: 16px">
            <%= @profile.user.email %></div>
            <%= f.input :address %>
            <%= f.input :description %>
            <%= f.input :avatar %>
            <%= f.input :avatar_cache, as: :hidden %>


            <div class="form-actions">
              <%= f.submit "Update profile", class: "btn btn-primary mb-5" %>
            </div>
            <%#= link_to "Delete", root_path, method: :delete, data: { confirm: "Are you sure you want to delete your profile?"} %>
        <% end %>
        </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>Profiles#new</h1>
<p>Find me in app/views/profiles/new.html.erb</p>

app/views/profiles/requests.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 col-lg-2">

      <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to "My Profile", profile_path(@profile), class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "My Artwork", profile_artworks_path(@profile), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Bookings", profile_bookings_path(@profile), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Requests", profile_requests_path(@profile), class: "active-tab nav-link"  %>
        </li>
      </ul>



    </div>
    <div class="col-12 col-lg-10">
      <h1 style="font-size: 32px; padding-bottom: 16px">My booking requests</h1>
      <div class="pb-5">

        <% my_artworks_with_bookings = current_user.artworks.reject { |artwork| artwork.bookings.empty?} %>
        <% if my_artworks_with_bookings.empty? %>
          <p style="font-size: 18px; padding-bottom: 16px">You currently have no booking requests</p>
        <% else %>
          <div class="pb-5">
            <% my_artworks_with_bookings.each do |artwork| %>
              <% artwork.bookings.each do |booking| %>
                <div style="display: flex; margin: 30px 0px">
                  <div class="image-status">
                    <%= link_to booking.artwork do %>
                      <img src='<%= booking.artwork.image %>' style="height: 220px; border-radius: 4px">
                    <% end %>
                    <p class="top-left" style="">Status: <%=  booking.status %> </p>
                  </div>
                  <div class="profile-description" style="padding: 8px 0px 8px 24px">
                    <h3 style="font-weight: 700">Request for: <%=  booking.artwork.title %> </h3>
                    <p style="margin: 8px 0px">Request from: <%=  booking.user.profile.first_name %> <%=  booking.user.profile.last_name %></p>
                    <p style="margin-top: 16px; margin-bottom: 0px">from <%= booking.start_date %></p>
                      <p style="margin: 8px 0px">until <%= booking.end_date %></p>

                    <% if booking.status != "Awaiting Confirmation" %>
                      <%= link_to("Confirm", bookings_confirm_path(booking), method: :post, data: { confirm: "Are you sure?" },class: "btn btn-primary mr-3 disabled", style: "min-width: 150px") %>
                      <%= link_to("Reject", bookings_reject_path(booking), method: :post,data: { confirm: "Are you sure?" },class: "btn btn-primary mr-3 disabled", style: "min-width: 150px") %>
                    <% else %>
                      <%= link_to("Confirm", bookings_confirm_path(booking), method: :post, data: { confirm: "Are you sure?" },class: "btn btn-primary mr-3", style: "min-width: 150px") %>
                      <%= link_to("Reject", bookings_reject_path(booking), method: :post,data: { confirm: "Are you sure?" },class: "btn btn-primary mr-3", style: "min-width: 150px") %>
                    <% end %>


                  </div>
                </div>
              <% end %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/profiles/show.html.erb
<div class="container">

  <div class="row mt-5">
    <div class="col-12 col-lg-2">
      <%= render 'shared/navigation' %>
    </div>
    <div class="col-12 col-lg-6">
      <h1 style="font-size: 32px">Hello, <%= @profile.first_name %>!</h1>
        <div class="profile-description">
        <p>First name</p>
        <h3> <%=  @profile.first_name %> </h3>
        <p>Last name</p>
        <h3> <%= @profile.last_name %></h3>
        <p>Email</p>
        <h3><%= @profile.user.email %></h3>
        <p>Address</p>
        <h3><%= @profile.address %></h3>
        <p>Description</p>
        <h3><%= @profile.description %></h3>
        <% if policy(@profile).edit? %>
          <%= link_to "Edit my profile", edit_profile_path(@profile), :class => "btn btn-primary px-5 my-5"  %>
        <% end %>
        </div>
    </div>
    <div class="col-12 col-lg-4">

<div class="artwork-img-box">
        <% if @profile.avatar? %>
          <%= cl_image_tag @profile.avatar,
          class: "artwork-img",
          style: "border-radius: 4px; filter: drop-shadow(0px 4px 4px #b7b7b7)"; %>
        <% end %>
      </div>

    </div>
  </div>
</div>