config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # get 'bookings/new'
  root to: 'pages#home'
  get 'profiles/:id/artworks', to: 'profiles#artworks', as: :profile_artworks
  get 'profiles/:id/requests', to: 'profiles#requests', as: :profile_requests
  get 'profiles/:id/bookings', to: 'profiles#bookings', as: :profile_bookings

  post 'bookings/:id/confirm', to: 'bookings#confirm', as: :bookings_confirm
  post 'bookings/:id/reject', to: 'bookings#reject', as: :bookings_reject


  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :artworks do
    resources :bookings, only: [:new, :create, :index]
  end
  resources :bookings, only: [:destroy]

  resources :profiles, except: [:index]

end

app/models/artwork.rb
class Artwork < ApplicationRecord
  belongs_to :user
  has_many :bookings
  mount_uploader :image, PhotoUploader
  validates :title, presence: true
  validates :description, presence: true
  validates :kind, presence: true
  validates :price, presence: true
  validates :tagline, presence: true, length: { minimum: 4 }
  validates :image, presence: true
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index

    if params[:search].present? && !params[:search_location].present?
      # first case : only the search by keyword
      @artworks_filter = search_by_keyword(params[:search])

    elsif !params[:search].present? && params[:search_location].present?
      # second case : only by location
      @artworks_filter = search_by_location(params[:search_location], params[:search_location_radius])

    elsif params[:search].present? && params[:search_location].present?
      # third case : both location and keyword
      @artworks_filter_by_keyword = search_by_keyword(params[:search])
      @artworks_filter_by_location = search_by_location(params[:search_location], params[:search_location_radius])

      @artworks_filter = @artworks_filter_by_keyword & @artworks_filter_by_location

    else
      # no search criterias : render everything !
      @artworks_filter = grab_all
    end

    if @artworks_filter == []
      @search_result_success = false
      @artworks_filter = grab_all
    else
      @search_result_success = true
    end

    #### to display the markers on the map for thoses with address
    @artworks_filter_with_gps = @artworks_filter.reject { |x| x.user.profile.latitude.nil? }

    @markers = @artworks_filter_with_gps.map do |artwork|
      {
        lat: artwork.user.profile.latitude,
        lng: artwork.user.profile.longitude,
        # to make that work : create a _infowindow partial into views/artworks !!!
        infoWindow: render_to_string(partial: "infowindow", locals: { artwork: artwork })
      }
    end
    ### end markers
  end

  def show
    @artwork = Artwork.find(params[:id])
    authorize @artwork

    if @artwork.user.profile.latitude
      @markers = [{
          lat: @artwork.user.profile.latitude,
          lng: @artwork.user.profile.longitude,
          # to make that work : create a _infowindow partial into views/artworks !!!
          infoWindow: render_to_string(partial: "infowindow_show", locals: { artwork: @artwork })
        }]
    end

  end

  def new
    @artwork = Artwork.new
    authorize @artwork
  end

  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.user = current_user
    authorize @artwork
    if @artwork.save
      redirect_to artwork_path(@artwork)
    else
      render :new
    end
  end

  def edit
    @artwork = Artwork.find(params[:id])
    session[:return_to] ||= request.referer
    authorize @artwork
  end

  def update
    @artwork = Artwork.find(params[:id])
    authorize @artwork
    if @artwork.update(artwork_params)
      redirect_to artwork_path(@artwork)
    else
      render :edit
    end
  end

  def destroy
    @artwork = Artwork.find(params[:id])
    authorize @artwork
    @artwork.destroy
    redirect_to profile_path(current_user)
  end

  private

  def artwork_params
    params.require(:artwork).permit(:title, :description, :image, :kind, :price, :width, :height, :tagline)
  end

  def grab_all
    policy_scope(Artwork).order(created_at: :desc)
  end

  def search_by_keyword(keyword)
    sql_query = "description ILIKE :query OR title ILIKE :query OR tagline ILIKE :query OR kind ILIKE :query"
    return policy_scope(Artwork).where(sql_query, query: "%#{keyword}%")
  end

  def search_by_location(location, radius)
    radius = 5 if radius == ""

    profiles_by_location = policy_scope(Profile).near("%#{location}%", radius)

    artworks_filter = []
    profiles_by_location.each do |profile|
      profile.user.artworks.each { |e| artworks_filter << e }
    end

    return artworks_filter
  end
end

app/views/artworks/_card.html.erb
<%= link_to artwork, class: "card-artwork" do %>
  <div class="card-trip">
    <img src='<%= artwork.image %>'>
    <div class="card-trip-infos">
      <div>
        <h2><%= artwork.title %></h2>
        <p><%= artwork.tagline %></p>
      </div>
      <h2 class="card-trip-pricing" style="font-weight: 500">€<%= artwork.price %></h2>
    </div>
  </div>
<% end %>

app/views/artworks/_infowindow.html.erb
<%= artwork.user.profile.address %> :
<ul>
  <% artwork.user.artworks.each do |art| %>
    <li>
      <%= link_to art do%>

        <img src='<%= art.image %>' style="height: 50px; border-radius: 4px">
        <%= art.title %>

      <% end %>
    </li>
  <% end %>
</ul>


  <%# artwork.user.artworks.each do |art| %>
    <!-- <li><img src='<%#= art.image %>' style="height: 50px; border-radius: 4px"> -->
    <%#= link_to art.title , art %>
  <!-- </li> -->
  <%# end %>

app/views/artworks/_infowindow_show.html.erb
<%= artwork.user.profile.first_name %>
<%= artwork.user.profile.last_name %>
<%= artwork.user.profile.address %>

app/views/artworks/edit.html.erb
<h1>Edit your artwork</h1>

<%= simple_form_for(@artwork) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.input :image_cache, as: :hidden %>
    <%= f.input :kind %>
    <%= f.input :price %>
    <%= f.input :width %>
    <%= f.input :height %>
    <%= f.input :tagline %>
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%#= link_to "Delete", root_path, method: :delete, data: { confirm: "Are you sure you want to delete your profile?"} %>
<% end %>

app/views/artworks/index.html.erb
<div class="container">
  <h1 class="pt-5 text-center">Art just for you!</h1>
  <div class="pt-2 pb-5 text-center">
  <% if @search_result_status %>
    <h2>Your selection : </h2>
  <% else %>
    <h2>Here's all what we have !</h2>
  <% end %>
  </div>

<div class="container mt-3 mb-5">
  <%= form_tag artworks_path, method: :get do %>
    <div class="row", style="display:flex; justify-content: space-between; align-items:flex-end">
      <div class="col-12 col-md-3">
        <div class="mx-3">
          <p style="font-weight: 500; font-size: 16px">Keyword</p>
          <%= search_field_tag :search,
              params[:search],
              class: "form-control search-navbar",
              style: "height: 48px; border-radius: 4px; width: 100%; box-shadow: 0 0 15px rgba(0,0,0,0.2);",
              placeholder: "Keyword"
            %>
        </div>
        </div>
        <div class="col-12 col-md-3">
          <div class="mx-3">
            <p style="font-weight: 500">Location</p>
            <%= text_field_tag :search_location,
              params[:search_location],
              class: "form-control search-navbar",
              style: "height: 48px; border-radius: 4px; width: 100%; box-shadow: 0 0 15px rgba(0,0,0,0.2);",
              placeholder: "Location"
            %>
          </div>
        </div>
        <div class="col-12 col-md-3">
          <div class="mx-3">
            <p style="font-weight: 500">Distance</p>
            <%= number_field_tag :search_location_radius,
              params[:search_location_radius],
              in: 0..100,
              class: "form-control search-navbar",
              style: "height: 48px; border-radius: 4px; width: 100%; box-shadow: 0 0 15px rgba(0,0,0,0.2);",
              placeholder: "Distance (in km)"
            %>
          </div>
        </div>
        <div class="col-12 col-md-3">
            <%= submit_tag 'Search',
              class: "searchbutton-navbar button-yellow btn btn-primary mr-3",
              style: "height: 48px; border-radius: 4px; width: 100%" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

  <div class="container">
    <div class="cards pb-5">
        <%= render partial: 'card', collection: @artworks_filter, as: :artwork %>
    </div>
  </div>
</div>

  <!-- Will display a map on the show page only if address a present -->
  <% if @markers %>
    <div
      id="map"
      style="width: 100%;
      height: 300px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
  <% end %>

app/views/artworks/new.html.erb
<div class="pt-5 container">

  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <h2>Upload your artwork</h2>
        <div class="form-inputs">

          <%= simple_form_for(@artwork) do |f| %>
              <%= f.input :title %>
              <%= f.input :tagline %>
              <%= f.input :description %>
              <%= f.input :image %>
              <%= f.input :image_cache, as: :hidden %>
              <%= f.input :kind %>
              <%= f.input :price %>
              <%= f.input :width %>
              <%= f.input :height %>

            <div class="form-actions">
              <%= f.submit "Create", class: "btn btn-primary mb-5" %>
            </div>
              <%#= link_to "Delete", root_path, method: :delete, data: { confirm: "Are you sure you want to delete your profile?"} %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/artworks/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 col-lg-4">
      <!-- I am not very convinced by this return, it is a javascript history link...Their is a other way to do by creating a new route, a new methode on the controller that will be called by the button and inside this methode "redirect_back(fallback_location: root_path)" (Agathe) -->
      <%= link_to "Back", :back, :class => "btn btn-primary mb-3" %>
      <h1><%= @artwork.title %></h1>
      <h3><%= @artwork.tagline %></h3>
      <div class="d-flex" style="margin-bottom: 24px;">
        <% if policy(@artwork).edit? %>
          <%= link_to "Edit Artwork", edit_artwork_path(@artwork), :class => "pl-0 btn bg-transparent text-secondary mr-3"  %>
        <% end %>
        <% if policy(@artwork).destroy? %>
          <%= link_to "Delete Artwork", artwork_path(@artwork), method: :delete, data: { confirm: "Are you sure?" } , :class => "btn bg-transparent text-secondary ml-3"  %>
        <% end %>
      </div>
      <div class="artwork-description">
        <h3>Description<h3>
        <p><%= @artwork.description %></p>
      </div>

      <div class="artwork-description">
        <h3>Price per day<h3>
        <p>EUR <%=  @artwork.price %></p>
      </div>

      <% if current_user %>
        <% if current_user.profile.last_name.nil?  && current_user.profile.address.nil?   %>
           <% if @artwork.user != current_user %>
              <%= link_to "Book now", edit_profile_path(current_user.profile),
                class: "btn btn-primary",
                style: "min-width: 150px"   %>
            <% else %>
              <%= link_to "Book now", new_artwork_booking_path(@artwork),
                class: "btn btn-primary",
                style: "min-width: 150px"  %>
            <% end %>
          <% else %>
          <% if @artwork.user != current_user %>
              <%= link_to "Book now", new_artwork_booking_path(@artwork),
                  class: "btn btn-primary",
                  style: "min-width: 150px"  %>

          <% end %>


        <% end %>
        <% else %>
        <%= link_to "Book now", new_user_registration_path,
                class: "btn btn-primary",
                style: "min-width: 150px"   %>
      <% end %>



    </div>

    <div class="col-12 col-lg-8" >
      <div class="artwork-img-box">
        <% if @artwork.image? %>
          <%= cl_image_tag @artwork.image, class: "artwork-img" %>
        <% end %>
      </div>
    </div>

  </div>

  <div class="row my-5">

    <div class="col-12 col-lg-4" >

    <% if @markers %>
      <div
        id="map"
        style="width: 100%;
        height: 300px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    <% end %>
   </div>

    <div class="col-12 col-lg-8">
      <div class="artwork-description" style="margin-top: 0px;">
        <h3>Artwork type<h3>
        <p><%= @artwork.kind %></p>
      </div>
      <div class="artwork-description">
        <h3>Object size<h3>
        <p><%= @artwork.width %>cm x <%= @artwork.height %>cm</p>
      </div>
      <div class="artwork-description">
        <h3>Location<h3>
        <p><%= @artwork.user.profile.address %></p>
      </div>
    </div>
  </div>
</div>