config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # get 'bookings/new'
  root to: 'pages#home'
  get 'profiles/:id/artworks', to: 'profiles#artworks', as: :profile_artworks
  get 'profiles/:id/requests', to: 'profiles#requests', as: :profile_requests
  get 'profiles/:id/bookings', to: 'profiles#bookings', as: :profile_bookings

  post 'bookings/:id/confirm', to: 'bookings#confirm', as: :bookings_confirm
  post 'bookings/:id/reject', to: 'bookings#reject', as: :bookings_reject


  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :artworks do
    resources :bookings, only: [:new, :create, :index]
  end
  resources :bookings, only: [:destroy]

  resources :profiles, except: [:index]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="centered footer-links" style="padding-top: 24px; padding-bottom: 12px">
      <a href="#" style="font-size: 16px">About</a>
      <a href="#" style="font-size: 16px">Contact</a>
      <a href="#" style="font-size: 16px">Terms</a>
      <a href="#" style="font-size: 16px">Careers</a>
    </div>
    <div class="centered footer-links" style="padding-bottom: 12px">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="centered footer-links" style="padding-bottom: 24px">
      Made with<i class="px-2 fas fa-heart"></i>  in Berlin
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-dark bg-primary navbar-lewagon sticky-top" style="padding-left: 24px; padding-right: 24px">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "MonaLeasing-Logo2.png" %>
    <% end %>



  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
           <%= render 'shared/search_bar' %>
        </li>
        <li class="nav-item">
          <% if current_user.nil? %>
            <%= link_to "Offer your Art", new_user_registration_path, class: "nav-button nav-link mx-3" %>
          <% elsif current_user.profile.last_name.nil?  && current_user.profile.address.nil?   %>
            <%= link_to "Offer your Art", edit_profile_path(current_user.profile), class: "nav-button nav-link mx-3" %>
          <% else %>
            <%= link_to "Offer your Art", new_artwork_path, class: "nav-button nav-link mx-3" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "All Artwork", artworks_path, class: "nav-button btn bg-transparent nav-link mr-3 px-3" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.profile.avatar? %>
            <%= cl_image_tag current_user.profile.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= image_tag "empty_avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "My artwork", profile_artworks_path(current_user), class: "dropdown-item" %>
            <%= link_to "My bookings", profile_bookings_path(current_user), class: "dropdown-item" %>
            <%= link_to "My booking requests", profile_requests_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navigation.html.erb
<ul class="nav flex-column">
  <li class="nav-item">
    <%= link_to "My Profile", profile_path(@profile), class: "active-tab nav-link"  %>
  </li>
  <li class="nav-item">
    <%= link_to "My Artwork", profile_artworks_path(@profile), class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "My Bookings", profile_bookings_path(@profile), class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "My Requests", profile_requests_path(@profile), class: "nav-link"  %>
  </li>
</ul>

app/views/shared/_search_bar.html.erb
<%= form_tag artworks_path, method: :get, :class => "form-inline" do %>
  <%= search_field_tag :search,
    params[:search],
    class: "form-control search-navbar ml-3",
    style: "height: 42px",
    placeholder: "Find a piece of art"
  %>
  <%= submit_tag 'Search',
    class: "searchbutton-navbar button-yellow btn btn-primary mr-3",
    style: "height: 42px; border: 2px solid white" %>
<% end %>